site_name: Magick Frames
markdown_extensions:
  - mermaid2
  - smarty
  - toc:
      permalink: true
  - sane_lists
nav:
  - Home: README.md
  - Styles: Styles.md
  - Examples: Examples.md
  - Command Line: CLI.md
  - How It Works: HowItWorks.md
  